### ISSUE TITLE
Implement github-actions-badge directly in shields.io

### ISSUE THREAD

**Issue by dougnukem** [CultureHQ/github-actions-badge#14]
Would it make more sense for this badge implementation to be part of the shields.io project itself. I can help adapting it to their structure from the lambda function.

- https://github.com/badges/shields/issues/2574
- https://github.com/badges/shields/blob/master/CONTRIBUTING.md

**Comment by kddnewton** [comment]
Closing this issue because I'm actually going to shut this down in favor of GitHub's baked-in one (https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg).
