### ISSUE TITLE
no runs

### ISSUE THREAD

**Issue by elgohr** [CultureHQ/github-actions-badge#15]
I'm using the badge in my repository https://github.com/elgohr/cf-jetbrains-license-server
Sadly the badge shows "no runs" since ever. When you click on the badge, you get to the successful build.

**Comment by kddnewton** [comment]
I wonder if it's cached in your browser? It's not doing that on mine. Can you try an incognito window? I recently pushed a new cache update so I wonder if that fixed it.

**Comment by elgohr** [comment]
This also happens in incognito mode. I also disabled the cache in Firefox (65.0.1).

**Comment by kddnewton** [comment]
That is so weird. It's showing success for me:

<img width="462" alt="Screen Shot 2019-03-17 at 9 05 40 AM" src="https://user-images.githubusercontent.com/5093358/54491311-e459e600-4893-11e9-9740-dfc3b135f914.png">

Honestly not sure how to fix this. We're serving ETags now and no-cache headers. Honestly I'm going to have to call this weird github/browser caching.

**Comment by elgohr** [comment]
Same here now. Thank you!
