### ISSUE TITLE
Support for multiple workflow definitions?

### ISSUE THREAD

**Issue by riker09** [CultureHQ/github-actions-badge#2]
Suppose I have more than one default workflow:

```hcl
# First workflow
workflow "Publish to NPM" {
  resolves = "Publish"
  on = "release"
}

action "Build" {
  uses = "actions/npm@e7aaefe"
  args = "install"
}

action "Test" {
  needs = "Build"
  uses = "actions/npm@e7aaefe"
  args = "test"
}

action "Tag" {
  needs = "Test"
  uses = "actions/bin/filter@master"
  args = "tag"
}

action "Publish" {
  uses = "actions/npm@e7aaefe"
  needs = ["Tag"]
  args = "publish --access public"
  env = {
    NPM_REGISTRY_URL = "https://registry.npmjs.org"
  }
  secrets = ["NPM_AUTH_TOKEN"]
}


# Second workflow
workflow "Test on Push" {
  resolves = "Test"
  on = "push"
}
```

I want the badge to reflect the value of the second workflow. How can I specify this in the image url?

Currently when multiple workflows are defined the status in my README.md is always "`null`".

**Comment by riker09** [comment]
I did a little digging and found out that the image that is displayed in my repo at the README.md seems to get cached. This is the HTML source code that is generated by GitHub:

```html
<img 
  src="https://camo.githubusercontent.com/5d40e9c62561d6ee67c461903b0ff101e41f19e3/68747470733a2f2f776470396677773072392e657865637574652d6170692e75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f64756374696f6e2f62616467652f4d657269666f6e644e65774d61726b6574732f69646f636f6e6669672d70726f76696465722d666f6c6465723f7374796c653d666c61742d737175617265" 
  alt="Build Status" 
  data-canonical-src="https://wdp9fww0r9.execute-api.us-west-2.amazonaws.com/production/badge/MerifondNewMarkets/idoconfig-provider-folder?style=flat-square" 
  style="max-width:100%;"
>
```

The canonical url generates the correct image. But where's the `camo.githubusercontent.com` stuff coming from?

**Comment by kddnewton** [comment]
Ok so there are a couple of things going on here:

- So right now with the GitHub api there's not really a way to distinguish between the different workflows short of using the internal ID (workflow name is not part of the API response). If you'd like to make a PR to support multiple workflows by checking the ID as an optional param, feel free but that's not something I have to time to work on just now.
- The caching stuff comes from GitHub itself. They're parsing the images within the markdown and proxying/caching them. This is presumably to do some kind of XSS protection.
- The workflow returning `null` is a bug that I need to fix. If the workflow hasn't run yet, `null` is returned for the last conclusion and it's not currently handled.

**Comment by kddnewton** [comment]
Unfortunately I'm not sure there's a way around the caching stuff. I'm returning `"Cache-Control": "no-cache"` but I think they're ignoring it.
