### ISSUE TITLE
not working on private repos

### ISSUE THREAD

**Issue by maxheld83** [CultureHQ/github-actions-badge#8]
this is a hunch based on anecdotal evidence, but I am guessing this currently does not work for private repos, because the AWS Lambda stuff can't, well, access private repos, naturally?

**Comment by kddnewton** [comment]
Yeah there's not really a way to do that without you deploying your own lambda and including a github key in the request unfortunately.

**Comment by maxheld83** [comment]
thanks, I thought so. Great work!

**Comment by caulagi** [comment]
Is there an example of how to include this key? I have tried to look at the code and figure out how I can make it work but it is not obvious to me.

**Comment by kddnewton** [comment]
Added a commented out line here: https://github.com/CultureHQ/github-actions-badge/blob/master/githubClient.js#L11. Just generate a token with `repo` permissions and you should be good to go.
